// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frhnemrbywrlytsouzuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyaG5lbXJieXdybHl0c291enVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NTE1MjksImV4cCI6MjA1MzEyNzUyOX0.-w0y3ffDJfuipMYsxF2TopSugJN_3miRM2sdhm3DrGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);